CREATE TABLE poll_candidate
(
    name character varying NOT NULL,
    poll_id character varying NOT NULL,
    id bigint NOT NULL DEFAULT nextval('poll_candidate_id_seq'::regclass),
    CONSTRAINT poll_candidate_pkey PRIMARY KEY (id),
    CONSTRAINT pollcandidate_to_poll_fk FOREIGN KEY (poll_id)
        REFERENCES public.poll (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE;
)